import { GetStaticProps } from 'next'
import { GraphQLClient, gql } from 'graphql-request'
import Head from 'next/head'
import { MainSlider } from '../components/MainSlider'
import { NewsSlider } from '../components/NewsSlider'

export interface Noticia {
  id: string,
  titulo: string,
  slug: string,
  dataPublicacao: string,
  conteudo:{
    html:string
  }
  imagemFundo: {
      url: string
  },
}

export interface Noticias{
  noticias: Noticia[] 
}

//type PageProps = InferGetStaticPropsType<typeof getStaticProps>

const graphcms = new GraphQLClient('https://api-sa-east-1.hygraph.com/v2/clas4yzfh7wpt01t7c71vcs7p/master')

const QUERY = gql`
  {
    noticias {
      id
      titulo
      slug
      dataPublicacao
      conteudo{
        html
      }
      imagemFundo{
        url
      }
    }
  }
`


export default function Home({ noticias }: Noticias) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainSlider />

      <main className='max-w-[1240px] m-auto mt-10'>
        <section className='mb-10 p-4'>
          <h2 className='mb-5 text-2xl font-extralight uppercase'>Notícias</h2>
          <NewsSlider noticias={noticias} />
        </section>

        <section className='mb-10 p-4'>
          <h2 className='mb-5 text-2xl font-extralight uppercase'>Prêmios</h2>
          <NewsSlider noticias={noticias} />
        </section>
        
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {

  const {noticias}:Noticias = await graphcms.request(QUERY)

  return {
    props: {
      noticias,
    },
  }
}


